{% set version = "25.2.3" %}

package:
  name: intel-media-driver
  version: {{ version }}

source:
  url: https://github.com/intel/media-driver/archive/refs/tags/intel-media-{{ version }}.tar.gz
  sha256: adc2968c49bcf5b7cc8bce09a785b96785cee10d577dac9eabb97f02916f7a22
  patches:
    - 0001-Remove-debugging-flag-to-slim-the-builds.patch

build:
  number: 0
  skip: true  # [not linux64]
  run_exports:
    - {{ pin_subpackage('intel-media-driver', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - pkg-config
  host:
    - libva
    - intel-gmmlib

test:
  commands:
    - test -f ${PREFIX}/lib/dri/iHD_drv_video.so

about:
  home: https://github.com/intel/media-driver
  summary: 'Intel(R) Media Driver for VAAPI'
  description: |
    The Intel(R) Media Driver for VAAPI is a new VA-API (Video Acceleration
    API) user mode driver supporting hardware accelerated decoding, encoding,
    and video post processing for GEN based graphics hardware.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - hmaarrfk
